server:
  port: 8002

cloud:
  gateway:
    uri: ${GATEWAY_URI}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}

spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://${AFLK_DB_URI}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${AFLK_DB_USERNAME}
    password: ${AFLK_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #ddl-auto: 'validate'
      ddl-auto=none:
    #show-sql: 'true'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

#SECRET KEY
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
token:
  access-expired-time : 3600000
  refresh-expired-time : 3600000